#+title: fyt, or "Freedom from YouTube"

A Babashka script meant to emulate the YouTube browsing experience from the comfort of your terminal, with none of the clutter (ads, recommendations, comments). MacOS-only, for the time being.

* Usage
IMPORTANT: You /must/ have =yt-dlp= in your =$PATH= for right now. =iina-cli= is optional, but it'll work out-of-the-box on a Homebrew MacOS install.

Run ~./fyt~ without any arguments to see what you can do. Currently supported: =search=, =play=, =dl=, and (for convenience) =alias=.

If you see a video ID that you'd like to watch later, you can use =alias= to give it a name that will link to the actual video by =play= and =dl=.

* Caveats
The biggest thing you'll notice is that =fyt search= creates a file called =.fyt-results= in the directory from which it is run. This isn't an accident, but it is an ugly workaround from YouTube video IDs being really unfun to type by hand or memorize. It's meant to be used in tandem with =alias=.

* Roadmap
The biggest goal is getting =search= to not be so dang ugly. The =.fyt-results= file is fine, but with luck it'll soon migrate to =$XDG_CACHE_HOME/fyt/results.edn=, so I wouldn't write anything to it.

Maybe I'll support a non-MacOS target at some point.

* Installation
Install by putting it in your =$PATH=, or if you're like me, ~cp fyt ~/bin/~.
